---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #  - name: ubuntu-16.04
  - name: centos-7.3
    attributes:
      elasticsearch:
        cluster_name: 'myorg-cluster1'
    tags:
      es_cluster: 'myorg-cluster1'

suites:
  - name: default
    run_list:
      - recipe[elasticsearch_reference::default]
      - recipe[elasticsearch_reference::sensu]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
